name: Bug report
description: File a bug report
body:
  - type: dropdown
    attributes:
      label: Bug presence
      description: Does this bug also occur without R.E.L.I.V.E.?
      options:
        - Yes
        - No
        - Unsure
      default: 2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating system
      description: On which Operating system did you encounter the bug?
      options:
        - Windows
        - Linux
        - macOS
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: How do we reproduce the bug?
    validations:
      required: false
  - type: textarea
  attributes:
    label: Game save file
    description: The game save files are located inside the game folder and end with .sav
    placeholder: Drag and drop your save file into this box.
  validations:
    required: false
  - type: markdown
    attributes:
    value: |
      You can find the R.E.L.I.V.E. log in your game directory e.g `C:\Program Files (x86)\Steam\steamapps\common\Oddworld Abes Exoddus\logs\myeasylog.log` if you installed the game through steam.
  - type: textarea
    attributes:
      label: R.E.L.I.V.E. logs may help us identify the issue.
      placeholder: Drag and drop myeasylog.log into this box.
    validations:
      required: true
